# Personal Info
title: "Masoud Ghasemi"
description: "Python Backend & AI Engineer"
author: "Masoud Ghasemi"
email: "masudpythongit@gmail.com"
phone: "(+98) 9010361944"
linkedin: "masoud-ghasemi-748412381"
github_username: "sorna-fast"

# Certificate Folder URL
certificates_folder: "https://github.com/sorna-fast/sorna-fast/tree/master/Certificate"

# Projects Data
projects:

  - name: "utkface-deep-learning-service"
    desc: "A facial recognition project to predict age, gender, race, etc....the project is under construction."
    url: "https://github.com/sorna-fast/utkface-deep-learning-service"
    tags: ["Deep Learning", "TensorFlow", "CNN","Fastapi"]

  - name: "TB Chest X-Ray Classifier"
    desc: "TB Chest X-Ray Classifier - Deep learning model for Tuberculosis detection using CNN architecture with 99.5% accuracy and 0.999 AUC score. "
    url: "https://github.com/sorna-fast/tb-chest-xray-classifier"
    tags: ["Deep Learning", "TensorFlow","Tuberculosis detection","Computer vision", "Medical AI", "CNN","chest-xray","Fastapi"]

  - name: "super-resolution-cnn-cifar10"
    desc: "Transform 16×16 low-resolution images to 32×32 high-quality versions using deep learning. Achieves PSNR 28.13 dB with lightweight CNN architecture "
    url: "https://github.com/sorna-fast/super-resolution-cnn-cifar10"
    tags: ["computer-vision", "deep-learning", "super-resolution","tensorflow/cnn"]

  - name: "EuroSAT CNN Classifier"
    desc: "Satellite Image Classification using CNN - EuroSAT Dataset Deep Learning model achieving 96.4% accuracy in land use recognition TensorFlow implementation with comprehensive analysis and visualizations "
    url: "https://github.com/sorna-fast/eurosat-cnn-classifier"
    tags: ["Python", "TensorFlow", "CNN","Data Augmentation","Image Processing"]

  - name: "Fraud-detection"
    desc: "Predicting transaction fraud using classification problems such as Guardian Boosting as well as user interfaces using Streamlite, Accuracy: 98% AUC-ROC "
    url: "https://github.com/sorna-fast/fraud-detection"
    tags: ["numpy", "pandas-dataframe","gradientboostingclassifier","randomforestclassifier","xgbclassifier","adaboostclassifier","streamlit-webapp"]

  - name: "Django Online Shop"
    desc: "Website project focusing on BKD programming with various features"
    url: "https://github.com/sorna-fast/django-online-shop"
    tags: ["Django", "ajax","mysql database","html css"]

  - name: "media-database-cs50sql"
    desc: "Final project for CS50 SQL – A normalized media database to manage movies, series, contributors, users, comments, and views."
    url: "https://github.com/sorna-fast/media-database-cs50sql"
    tags: ["SQL", "SQL-SERVER", "SQL-Queries", "SQL-Schema"]

  - name: "food-store-database-mongodb"
    desc: "Food store database with all orders and database records"
    url: "https://github.com/sorna-fast/food-store-database-mongodb"
    tags: ["MongoDB", "NoSQL Database","NoSQL Queries","Nosql store"]
